apiVersion: apps/v1
kind: Deployment
metadata:
  name: petback-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petback
  template:
    metadata:
      labels:
        app: petback
    spec:
      containers:
      - name: petback
        image: your-docker-hub-repo/petback:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: backend-config-volume
          mountPath: /app/config.json
          subPath: backend_config.json
      volumes:
      - name: backend-config-volume
        secret:
          secretName: backend-config
