version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: petback
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - petnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: petfront
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /home/ec2-user/PET_NGO/frontend/config/config.json:/app/petfront/config/config.json:ro
    networks:
      - petnet

networks:
  petnet:
    driver: bridge
