apiVersion: apps/v1
kind: Deployment
metadata:
  name: petfront-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petfront
  template:
    metadata:
      labels:
        app: petfront
    spec:
      containers:
      - name: petfront
        image: your-docker-hub-repo/petfront:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: frontend-config-volume
          mountPath: /app/config/config.json
          subPath: frontend_config.json
      volumes:
      - name: frontend-config-volume
        secret:
          secretName: frontend-config
